name: Hello World Java Workflow

on: push 

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code 
        uses: actions/checkout@v3 

      - name: Say Hello
        run: echo "Hello, World!" 
